import networkx as nx
from .misc import naive_title_extraction, extract_proposed_title
import copy
import yaml

def conversation_to_graph(conv):        
    
    G = nx.DiGraph()
    
    # TODO: loop over conversations
    #conv_id = 96 #270
    #G.add_nodes_from(convs[conv_id]['mapping'].items(), data=True)
    #G.add_nodes_from(conv['mapping'].items(), data=True)
    nodes = conv.pop('mapping')
    G.add_nodes_from(nodes.items(), data=True)
    nx.set_node_attributes(G, conv, 'conversation_metadata')



    #nx.set_node_attributes(G, conv['conversation_id'], 'conversation_id')
    #nx.set_node_attributes(G, conv['title'], 'conversation_title')

    # actually, instead of looping over conversations, we can use that networkx method
    # can't remember what it's called... would let us add the conversation-wide node attributes
    # to all those nodes that share the same conversation.
    
    
    for name, node in G.nodes(data=True):
        if node.get('children'):
            G.add_edges_from([(name, child) for child in node['children']])
        if node.get('parent'):
            G.add_edge(node['parent'], name)

    return G

def process_conversation_graph__prompt_and_title(G):
           
    for _, node in G.nodes(data=True):
        if not node['message']:
            continue
    
        if node['message']['author']['role'] != 'assistant':
            continue
    
        ### Get prompt
        parent_node = G.nodes(data=True)[node['parent']]
        # uh.... gonna have to fix this. 
        # I guess this code worked for the simple "gadget" or whatever, but not for the full featured interface
        #parent_prompt = ''.join(parent_node['message']['content']['parts'])
        parent_prompt=None
        parts = parent_node['message']['content'].get('parts')
        try:
            if parts:
                #print(parts)
                parent_prompt = ''.join(parts)
            node['prompt'] = parent_prompt
        except TypeError:
            continue

        content = node['message']['content'].get('parts')
        if not content:
            content = node['message']['content'].get('text')
        else:
            content = ''.join(node['message']['content']['parts'])
        if not content:
            continue
        naive_title = naive_title_extraction(content)
        if naive_title:
            node['title'] = naive_title
            content = '\n'.join(content.split('\n')[1:]).strip() # drop first line
        else:
            #title = suggest_title(content)
            title = extract_proposed_title(content)
            if title:
                node['title']=title
            else:
                node['title']=suggest_title(content)
        node['processed'] = content
    return G

def link_prompts_back_to_source_spans(G):
    for _, node in G.nodes(data=True):
        if not node['message']:
            continue
        if node['message']['author']['role'] != 'assistant':
            continue
        title = node['title']
        prompt = node['prompt']
        if prompt.startswith(">"):
            prompt = prompt[1:].split('\n')[0]
        ancestors = nx.ancestors(G, node['id'])
        hits = []
        for candidate in ancestors:
            if candidate['message']['author']['role'] != 'assistant':
                continue
            if title.lower() in candidate['processed'].lower():
                hits.append(candidate)
            elif prompt.lower() in candidate['processed'].lower():
                hits.append(candidate)
            # TODO: 
            # - add wikilinks to candidate
            # - add backlinks to article node
    return G


def subgraphs_to_articles(subgraphs):
    articles = []
    for G in subgraphs:
        for node_id, node in G.nodes(data=True):
            if 'processed' not in node:
                continue
            link_candidates = []
            neighbors = nx.neighbors(G, node_id)
            for candidate_id in neighbors:
                candidate = G.nodes(data=True)[candidate_id]
                if candidate.get('article_title'):
                    link_candidates.append(candidate['article_title'])
                
            metadata = dict(
                conversation_id=node['conversation_metadata']['conversation_id'],
                message_id=node['message']['id'],
                message_create_time=node['message']['create_time'],
                tags=["autogenerated","uncurated", f"prune/conv_id/{node['conversation_metadata']['conversation_id']}"],
                #entities=[],
                create_time=node['message']['create_time'],
                gizmo_id=node['message'].get('metadata',{}).get('gizmo_id'),
                model_slug=node['message'].get('metadata',{}).get('model_slug'),
                inferred_article_title=node.get('article_title'),
                conversation_title=node['conversation_metadata']['title'],
                #prompt=node['prompt']# F hmm.
            )
            if node.get('prompt'):
                metadata['prompt']=node['prompt']

            content = f"---\n{yaml.dump(metadata)}---\n\n{node['processed']}"
            article=dict(metadata=metadata, content=content)
            articles.append(article)
    return articles


# TODO:
#
# * connect prompts/quotes and make links
#   - start by collecting prompts and subsequent titles and matching those into the responses across the conversation
#   - should probably also link to the preceding response for conversation tracking
#   - prompts that are quoted sections from prior articles should become links if the response is an article and not a continuation
#
# * timestampes -> human readable time
# * replace \\( math with \\[ math
#
# * figure out which responses are continuations rather than new articles
#   - For now, assume each one is a new article and consider "contracting" (combining) articles later.
#   - maybe focus on responses where prompts were long or otherwise don't look like titles
#
# * assign tags
#   - at very least, `auto-ingested/needs-review` or something like that
#
# * build frontmatter
#   - tags
#   - misc node data attributes (id, created_time, ... the works)
#
# * flag content that looks like it was already added manually
#   - use `before -> after` to develop annotations to finetune/train a classifier to suggest links
#
#
# DONE:
#
# * attach prompts to the responses they generated
#   - they're already "attached" in the graph, but i want to push the prompt text
#     as an attribute on the response nodes
#   - assistant responses should carry their parent prompt as an attribute